// <auto-generated />
namespace SNOW_Solution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class run_first : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(run_first));
        
        string IMigrationMetadata.Id
        {
            get { return "201609011011026_run_first"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
